# Generated by Django 5.1 on 2024-08-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='manufacturer',
            new_name='mark',
        ),
        migrations.AddField(
            model_name='produtos',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
